spring.application.name=Task-Manager-Application

server.port=8080

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Redis configuration
#spring.data.redis.host=${REDIS_HOST}
#spring.data.redis.port=${REDIS_PORT}
#spring.data.redis.username=${REDIS_USERNAME:default}
#spring.data.redis.password=${REDIS_PASSWORD}